// default package
// Generated 3 Oct, 2017 11:06:10 AM by Hibernate Tools 5.1.5.Final
package com.bing.model;
import java.util.HashSet;
import java.util.Set;

/**
 * Gterperson generated by hbm2java
 */
public class Gterperson implements java.io.Serializable {

	private Integer id;
	private String ielts;
	private String toefl;
	private String gre;
	private String gmat;
	private String other;
	private String cnUniversity;
	private String cnMajor;
	private String cnGpa;
	private String cnNote;
	private Set gteroffers = new HashSet(0);

	public Gterperson() {
	}

	public Gterperson(String ielts, String toefl, String gre, String gmat, String other, String cnUniversity,
			String cnMajor, String cnGpa, String cnNote, Set gteroffers) {
		this.ielts = ielts;
		this.toefl = toefl;
		this.gre = gre;
		this.gmat = gmat;
		this.other = other;
		this.cnUniversity = cnUniversity;
		this.cnMajor = cnMajor;
		this.cnGpa = cnGpa;
		this.cnNote = cnNote;
		this.gteroffers = gteroffers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getIelts() {
		return this.ielts;
	}

	public void setIelts(String ielts) {
		this.ielts = ielts;
	}

	public String getToefl() {
		return this.toefl;
	}

	public void setToefl(String toefl) {
		this.toefl = toefl;
	}

	public String getGre() {
		return this.gre;
	}

	public void setGre(String gre) {
		this.gre = gre;
	}

	public String getGmat() {
		return this.gmat;
	}

	public void setGmat(String gmat) {
		this.gmat = gmat;
	}

	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	public String getCnUniversity() {
		return this.cnUniversity;
	}

	public void setCnUniversity(String cnUniversity) {
		this.cnUniversity = cnUniversity;
	}

	public String getCnMajor() {
		return this.cnMajor;
	}

	public void setCnMajor(String cnMajor) {
		this.cnMajor = cnMajor;
	}

	public String getCnGpa() {
		return this.cnGpa;
	}

	public void setCnGpa(String cnGpa) {
		this.cnGpa = cnGpa;
	}

	public String getCnNote() {
		return this.cnNote;
	}

	public void setCnNote(String cnNote) {
		this.cnNote = cnNote;
	}

	public Set getGteroffers() {
		return this.gteroffers;
	}

	public void setGteroffers(Set gteroffers) {
		this.gteroffers = gteroffers;
	}
	public void updatePersonDetails(String name, String val){
		if(name.equals("本科学校档次:")){
			this.cnUniversity=val;
		}
		else if(name.equals("本科专业:")){
			this.cnMajor=val;
		}
		else if(name.equals("本科成绩和算法、排名:")){
			this.cnGpa=val;
		}
		else if(name.equals("其他说明:")){
			this.cnNote=val;
		}
		//language grade
		else if(name.equals("IELTS:")){
			this.ielts=val;
		}
		else if(name.equals("TOFEL:")){
			this.toefl=val;
		}
		else if(name.equals("GRE:")){
			this.gre=val;
		}
		else if(name.equals("GMAT:")){
			this.gmat=val;
		}
		else {
			this.other=val;
		}
	}
}
