// default package
// Generated 3 Oct, 2017 11:06:10 AM by Hibernate Tools 5.1.5.Final
package com.bing.model;
/**
 * Gteroffer generated by hbm2java
 */
public class Gteroffer implements java.io.Serializable {

	private Integer id;
	private Gterperson gterperson;
	private String university;
	private String major;
	private String result;
	private String degree;
	private String informDate;
	private String enterDate;
	private String enterSemester;
	private String link;

	public Gteroffer() {
	}

	public Gteroffer(Gterperson gterperson, String university, String major, String result, String degree,
			String informDate, String enterDate, String enterSemester, String link) {
		this.gterperson = gterperson;
		this.university = university;
		this.major = major;
		this.result = result;
		this.degree = degree;
		this.informDate = informDate;
		this.enterDate = enterDate;
		this.enterSemester = enterSemester;
		this.link = link;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Gterperson getGterperson() {
		return this.gterperson;
	}

	public void setGterperson(Gterperson gterperson) {
		this.gterperson = gterperson;
	}

	public String getUniversity() {
		return this.university;
	}

	public void setUniversity(String university) {
		this.university = university;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getInformDate() {
		return this.informDate;
	}

	public void setInformDate(String informDate) {
		this.informDate = informDate;
	}

	public String getEnterDate() {
		return this.enterDate;
	}

	public void setEnterDate(String enterDate) {
		this.enterDate = enterDate;
	}

	public String getEnterSemester() {
		return this.enterSemester;
	}

	public void setEnterSemester(String enterSemester) {
		this.enterSemester = enterSemester;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}
	public void updateOffer(String name, String val){
		//initialize offer
		if(name.equals("申请学校:")){
			this.university=val;
		}
		else if(name.equals("学位:")){
			this.degree=val;
		}
		else if(name.equals("专业:")){
			this.major=val;
		}
		else if(name.equals("申请结果:")){
			setResult(val);
		}
		else if(name.equals("入学年份:")){
			this.enterDate=val;
		}
		else if(name.equals("入学学期:")){
			this.enterSemester=val;
		}
		else if(name.equals("通知时间:")){
			this.informDate=val;
		}
	}
}
